[package]
name = "monster"
version = "0.1.0"
description = "Example demo monster NFT"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "monster"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.19.0"
sha256 = "1.0.3"
